export const tableColumns = {
    'idPlan': {name: 'Identificación del plan', type: 'text', visible: true},
    'documento': {name: 'Documento de identificación', type: 'text', visible: true},
    'nombre': {name: 'Apellidos y nombre del profesor', type: 'text', visible: true},
    'tipoEmpleado': {name: 'Tipo de vinculación', type: 'text', visible: true},
    'dedicacion': {name: 'dedicacion', type: 'text', visible: true},
    'docencia': {name: 'docencia', type: 'text', visible: true},
    'otrasDocencias': {name: 'otras_doce', type: 'text', visible: true},
    'investigacion': {name: 'investigac', type: 'text', visible: true},
    'otrasInvestigaciones': {name: 'otras_inve', type: 'text', visible: true},
    'extension': {name: 'extension', type: 'text', visible: true},
    'otrasExtensiones': {name: 'otras_exte', type: 'text', visible: true},
    'admon': {name: 'admon', type: 'text', visible: true},
    'otras': {name: 'otras', type: 'text', visible: true},
    'idEstado': {name: 'id_estado', type: 'text', visible: false},
    'codigoFacultad': {name: 'codfac', type: 'text', visible: false},
    'idCentroCosto': {name: 'ccosto_pro', type: 'text', visible: false},
    'centroCosto': {name: 'ccosto', type: 'text', visible: false},
    'centroCostoDesc': {name: 'ccosto_desc', type: 'text', visible: false},
    'semestre': {name: 'stre_plan', type: 'text', visible: true},
    'diasPlan': {name: 'dias_plan', type: 'text', visible: true}
};
